# Generated by Django 5.1.5 on 2025-01-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_useraccount_groups_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='user_account_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='user_account_permissions', to='auth.permission'),
        ),
    ]
