# Generated by Django 5.1.5 on 2025-01-28 15:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_useraccount_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='user_image'),
        ),
    ]
